import { ClubData } from "@/components/clubs/club-card";

export const CLUBS_DATA: ClubData[] = [
  {
    id: "tada-badminton-club",
    name: "Tada Badminton Club",
    logoText: "TADA BADMINTON",
    coverUrl: "/images/clubs/tada-club.png",
    rating: 4.9,
    reviewCount: 342,
    memberCount: 1248,
    location: "Quận 7, TP. HCM",
    sport: "Cầu lông",
    statusText: "Hoạt động hôm nay",
    isVerified: true,
    isVip: true,
  },
  {
    id: "saigon-smash",
    name: "Saigon Smash Pickleball",
    logoText: "SAIGON SMASH",
    coverUrl: "/images/clubs/saigon-smash.png",
    rating: 4.8,
    reviewCount: 215,
    memberCount: 856,
    location: "Quận 1, TP. HCM",
    sport: "Pickleball",
    statusText: "Đang tuyển thành viên",
    isVerified: true,
    isVip: true,
  },
  {
    id: "district-7-players",
    name: "District 7 Football Club",
    logoText: "D7 PLAYERS",
    coverUrl: "/images/clubs/d7-players.png",
    rating: 4.7,
    reviewCount: 168,
    memberCount: 432,
    location: "Quận 7, TP. HCM",
    sport: "Bóng đá",
    statusText: "Hoạt động tích cực",
    isVerified: true,
    isVip: true,
  },
  {
    id: "saigon-tennis-club",
    name: "Saigon Tennis Master Club",
    logoText: "SAIGON TENNIS",
    coverUrl: "/images/clubs/saigon-tennis.png",
    rating: 4.9,
    reviewCount: 198,
    memberCount: 620,
    location: "Quận 2, TP. HCM",
    sport: "Tennis",
    statusText: "Hoạt động hàng tuần",
    isVerified: true,
    isVip: true,
  },
  {
    id: "hanoi-shuttlecock-club",
    name: "Hà Nội Shuttlecock Club",
    logoText: "HANOI SHUTTLE",
    coverUrl: "/images/clubs/tada-club.png",
    rating: 4.8,
    reviewCount: 175,
    memberCount: 512,
    location: "Cầu Giấy, Hà Nội",
    sport: "Cầu lông",
    statusText: "Tuyển hội viên mới",
    isVerified: true,
    isVip: false,
  },
  {
    id: "danang-pickleball-warriors",
    name: "Đà Nẵng Pickleball Warriors",
    logoText: "DN WARRIORS",
    coverUrl: "/images/clubs/saigon-smash.png",
    rating: 4.9,
    reviewCount: 140,
    memberCount: 390,
    location: "Sơn Trà, Đà Nẵng",
    sport: "Pickleball",
    statusText: "Giao lưu hàng ngày",
    isVerified: true,
    isVip: true,
  },
];
