export interface LeaderboardPlayer {
  id: string;
  rank: number;
  previousRank: number;
  trend: "up" | "down" | "same";
  rankChange?: number;
  name: string;
  avatarUrl: string;
  heroImageUrl?: string;
  isVerified: boolean;
  clubName: string;
  city: string;
  district?: string;
  category:
    | "singles_men"
    | "singles_women"
    | "doubles_men"
    | "doubles_women"
    | "doubles_mixed"
    | "teams";
  level: string; // e.g. "4.5+ (Bán chuyên)", "3.5 - 4.5 (Nâng cao)", "2.5 - 3.5 (Phong trào)"
  levelTier: "pro" | "advanced" | "grassroots" | "newbie";
  eloPoints: number;
  matchesPlayed: number;
  matchesWon: number;
  winRate: number; // percentage
  tournamentsJoined: number;
  trophiesCount: number;
  currentStreak: string; // e.g. "W8", "W3"
  recentForm: ("W" | "L")[];
  bio?: string;
}

export const BADMINTON_LEADERBOARD_DATA: LeaderboardPlayer[] = [
  {
    id: "bm-player-1",
    rank: 1,
    previousRank: 1,
    trend: "same",
    name: "Nguyễn Tiến Minh",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    heroImageUrl: "/images/rankings/tien-minh.png",
    isVerified: true,
    clubName: "CLB Cầu Lông Hà Nội Pro",
    city: "Hà Nội",
    district: "Đống Đa",
    category: "singles_men",
    level: "4.5+ (Huyền thoại / Pro)",
    levelTier: "pro",
    eloPoints: 2860,
    matchesPlayed: 48,
    matchesWon: 42,
    winRate: 88,
    tournamentsJoined: 24,
    trophiesCount: 18,
    currentStreak: "W8",
    recentForm: ["W", "W", "W", "W", "W"],
    bio: "Vận động viên kỳ cựu số 1 Việt Nam, duy trì phong độ đỉnh cao với lối đánh bền bỉ và điều cầu chuẩn xác.",
  },
  {
    id: "bm-player-2",
    rank: 2,
    previousRank: 3,
    trend: "up",
    rankChange: 1,
    name: "Lê Đức Phát",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    heroImageUrl: "/images/activities/badminton-hero.png",
    isVerified: true,
    clubName: "CLB Quân Đội / PlayGrid Stars",
    city: "Hà Nội",
    district: "Ba Đình",
    category: "singles_men",
    level: "4.5+ (Đội Tuyển QG)",
    levelTier: "pro",
    eloPoints: 2780,
    matchesPlayed: 42,
    matchesWon: 36,
    winRate: 86,
    tournamentsJoined: 20,
    trophiesCount: 12,
    currentStreak: "W5",
    recentForm: ["W", "W", "W", "L", "W"],
    bio: "Tay vợt trẻ hàng đầu với những cú đập cầu smash uy lực lên tới 390 km/h.",
  },
  {
    id: "bm-player-3",
    rank: 3,
    previousRank: 2,
    trend: "down",
    rankChange: 1,
    name: "Nguyễn Thùy Linh",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    heroImageUrl: "/images/activities/badminton-banner.png",
    isVerified: true,
    clubName: "CLB Ciputra Hà Nội",
    city: "Phú Thọ",
    district: "Việt Trì",
    category: "singles_women",
    level: "4.5+ (Đội Tuyển QG)",
    levelTier: "pro",
    eloPoints: 2750,
    matchesPlayed: 39,
    matchesWon: 33,
    winRate: 85,
    tournamentsJoined: 21,
    trophiesCount: 14,
    currentStreak: "W4",
    recentForm: ["W", "W", "L", "W", "W"],
    bio: "Hoa khôi cầu lông Việt Nam, kỹ thuật thanh thoát và tốc độ di chuyển biến hóa.",
  },
  {
    id: "bm-player-4",
    rank: 4,
    previousRank: 4,
    trend: "same",
    name: "Phạm Cao Cường",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    isVerified: true,
    clubName: "CLB Thể Thao Phú Thọ",
    city: "TP. Hồ Chí Minh",
    district: "Quận 11",
    category: "singles_men",
    level: "4.0 - 4.5 (Bán chuyên)",
    levelTier: "advanced",
    eloPoints: 2620,
    matchesPlayed: 35,
    matchesWon: 28,
    winRate: 80,
    tournamentsJoined: 16,
    trophiesCount: 8,
    currentStreak: "W3",
    recentForm: ["W", "W", "W", "L", "W"],
  },
  {
    id: "bm-player-5",
    rank: 5,
    previousRank: 6,
    trend: "up",
    rankChange: 1,
    name: "Nguyễn Hải Đăng",
    avatarUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80",
    isVerified: true,
    clubName: "CLB VNB Sports Tân Bình",
    city: "TP. Hồ Chí Minh",
    district: "Tân Bình",
    category: "singles_men",
    level: "4.0 - 4.5 (Bán chuyên)",
    levelTier: "advanced",
    eloPoints: 2580,
    matchesPlayed: 32,
    matchesWon: 25,
    winRate: 78,
    tournamentsJoined: 15,
    trophiesCount: 6,
    currentStreak: "W2",
    recentForm: ["W", "L", "W", "W", "W"],
  },
  {
    id: "bm-player-6",
    rank: 6,
    previousRank: 5,
    trend: "down",
    rankChange: 1,
    name: "Vũ Thị Trang",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    isVerified: true,
    clubName: "CLB Cầu Lông Bắc Giang",
    city: "Bắc Giang",
    category: "singles_women",
    level: "4.0 - 4.5 (Bán chuyên)",
    levelTier: "advanced",
    eloPoints: 2520,
    matchesPlayed: 30,
    matchesWon: 23,
    winRate: 77,
    tournamentsJoined: 14,
    trophiesCount: 7,
    currentStreak: "L1",
    recentForm: ["L", "W", "W", "W", "W"],
  },
  {
    id: "bm-player-7",
    rank: 7,
    previousRank: 8,
    trend: "up",
    rankChange: 1,
    name: "Trần Anh Tuấn & Lê Minh Khoa (Đôi Nam)",
    avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    isVerified: true,
    clubName: "CLB Tada Badminton",
    city: "TP. Hồ Chí Minh",
    district: "Quận 7",
    category: "doubles_men",
    level: "4.0 (Nâng cao)",
    levelTier: "advanced",
    eloPoints: 2470,
    matchesPlayed: 28,
    matchesWon: 22,
    winRate: 79,
    tournamentsJoined: 12,
    trophiesCount: 5,
    currentStreak: "W3",
    recentForm: ["W", "W", "W", "L", "W"],
  },
  {
    id: "bm-player-8",
    rank: 8,
    previousRank: 7,
    trend: "down",
    rankChange: 1,
    name: "Nguyễn Văn Hùng & Đỗ Thu Thảo (Đôi Nam Nữ)",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    isVerified: true,
    clubName: "CLB Cầu Lông Khang An",
    city: "TP. Hồ Chí Minh",
    district: "Thủ Đức",
    category: "doubles_mixed",
    level: "3.5 - 4.0 (Phong trào Khá)",
    levelTier: "advanced",
    eloPoints: 2410,
    matchesPlayed: 26,
    matchesWon: 20,
    winRate: 77,
    tournamentsJoined: 11,
    trophiesCount: 4,
    currentStreak: "W2",
    recentForm: ["W", "W", "L", "W", "L"],
  },
  {
    id: "bm-player-9",
    rank: 9,
    previousRank: 10,
    trend: "up",
    rankChange: 1,
    name: "Hoàng Văn Nam",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    isVerified: false,
    clubName: "CLB Cầu Lông Cầu Giấy",
    city: "Hà Nội",
    district: "Cầu Giấy",
    category: "singles_men",
    level: "3.5 (Phong trào)",
    levelTier: "grassroots",
    eloPoints: 2350,
    matchesPlayed: 25,
    matchesWon: 18,
    winRate: 72,
    tournamentsJoined: 9,
    trophiesCount: 3,
    currentStreak: "W1",
    recentForm: ["W", "L", "W", "L", "W"],
  },
  {
    id: "bm-player-10",
    rank: 10,
    previousRank: 9,
    trend: "down",
    rankChange: 1,
    name: "Đặng Thị Thúy Hằng",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    isVerified: true,
    clubName: "CLB Thể Thao Viettel",
    city: "TP. Hồ Chí Minh",
    district: "Quận 10",
    category: "singles_women",
    level: "3.5 (Phong trào)",
    levelTier: "grassroots",
    eloPoints: 2310,
    matchesPlayed: 22,
    matchesWon: 16,
    winRate: 73,
    tournamentsJoined: 8,
    trophiesCount: 2,
    currentStreak: "L1",
    recentForm: ["L", "W", "W", "L", "W"],
  },
  {
    id: "bm-player-11",
    rank: 11,
    previousRank: 12,
    trend: "up",
    rankChange: 1,
    name: "CLB Tada Badminton (Đồng Đội)",
    avatarUrl: "/images/clubs/tada-club.png",
    isVerified: true,
    clubName: "Tada Badminton Club",
    city: "TP. Hồ Chí Minh",
    district: "Quận 7",
    category: "teams",
    level: "Hạng Đội CLB Xuất Sắc",
    levelTier: "pro",
    eloPoints: 3450,
    matchesPlayed: 64,
    matchesWon: 56,
    winRate: 88,
    tournamentsJoined: 32,
    trophiesCount: 16,
    currentStreak: "W9",
    recentForm: ["W", "W", "W", "W", "W"],
  },
  {
    id: "bm-player-12",
    rank: 12,
    previousRank: 11,
    trend: "down",
    rankChange: 1,
    name: "CLB Cầu Lông Khang An (Đồng Đội)",
    avatarUrl: "/images/explore_sports/gridy-badminton.avif",
    isVerified: true,
    clubName: "CLB Khang An Thủ Đức",
    city: "TP. Hồ Chí Minh",
    district: "Thủ Đức",
    category: "teams",
    level: "Hạng Đội CLB",
    levelTier: "advanced",
    eloPoints: 3280,
    matchesPlayed: 58,
    matchesWon: 48,
    winRate: 83,
    tournamentsJoined: 28,
    trophiesCount: 11,
    currentStreak: "W4",
    recentForm: ["W", "W", "W", "L", "W"],
  },
];

export const CITIES_LIST = [
  "Tất cả địa điểm",
  "Hà Nội",
  "TP. Hồ Chí Minh",
  "Đà Nẵng",
  "Phú Thọ",
  "Bắc Giang",
  "Bình Dương",
  "Hải Phòng",
];

export const CATEGORY_TABS = [
  { id: "all", label: "Tất cả hạng mục" },
  { id: "singles_men", label: "Đơn Nam" },
  { id: "singles_women", label: "Đơn Nữ" },
  { id: "doubles_men", label: "Đôi Nam" },
  { id: "doubles_mixed", label: "Đôi Nam Nữ" },
  { id: "teams", label: "Câu Lạc Bộ / Đội" },
];

export const LEVEL_TIERS = [
  { id: "all", label: "Tất cả trình độ" },
  { id: "pro", label: "Chuyên nghiệp / Pro (4.5+)" },
  { id: "advanced", label: "Nâng cao (3.5 - 4.5)" },
  { id: "grassroots", label: "Phong trào (2.5 - 3.5)" },
];
