export const countriesList = [
  { code: "vn", vi: "Việt Nam", en: "Vietnam" },
  { code: "af", vi: "Afghanistan", en: "Afghanistan" },
  { code: "al", vi: "Albania", en: "Albania" },
  { code: "dz", vi: "Algeria", en: "Algeria" },
  { code: "ad", vi: "Andorra", en: "Andorra" },
  { code: "ao", vi: "Angola", en: "Angola" },
  { code: "ag", vi: "Antigua và Barbuda", en: "Antigua and Barbuda" },
  { code: "ar", vi: "Argentina", en: "Argentina" },
  { code: "am", vi: "Armenia", en: "Armenia" },
  { code: "au", vi: "Úc", en: "Australia" },
  { code: "at", vi: "Áo", en: "Austria" },
  { code: "az", vi: "Azerbaijan", en: "Azerbaijan" },
  { code: "bs", vi: "Bahamas", en: "Bahamas" },
  { code: "bh", vi: "Bahrain", en: "Bahrain" },
  { code: "bd", vi: "Bangladesh", en: "Bangladesh" },
  { code: "bb", vi: "Barbados", en: "Barbados" },
  { code: "by", vi: "Belarus", en: "Belarus" },
  { code: "be", vi: "Bỉ", en: "Belgium" },
  { code: "bz", vi: "Belize", en: "Belize" },
  { code: "bj", vi: "Benin", en: "Benin" },
  { code: "bt", vi: "Bhutan", en: "Bhutan" },
  { code: "bo", vi: "Bolivia", en: "Bolivia" },
  { code: "ba", vi: "Bosnia và Herzegovina", en: "Bosnia and Herzegovina" },
  { code: "bw", vi: "Botswana", en: "Botswana" },
  { code: "br", vi: "Brazil", en: "Brazil" },
  { code: "bn", vi: "Brunei", en: "Brunei" },
  { code: "bg", vi: "Bulgaria", en: "Bulgaria" },
  { code: "bf", vi: "Burkina Faso", en: "Burkina Faso" },
  { code: "bi", vi: "Burundi", en: "Burundi" },
  { code: "kh", vi: "Campuchia", en: "Cambodia" },
  { code: "cm", vi: "Cameroon", en: "Cameroon" },
  { code: "ca", vi: "Canada", en: "Canada" },
  { code: "cv", vi: "Cape Verde", en: "Cape Verde" },
  { code: "cf", vi: "Cộng hòa Trung Phi", en: "Central African Republic" },
  { code: "td", vi: "Chad", en: "Chad" },
  { code: "cl", vi: "Chile", en: "Chile" },
  { code: "cn", vi: "Trung Quốc", en: "China" },
  { code: "co", vi: "Colombia", en: "Colombia" },
  { code: "km", vi: "Comoros", en: "Comoros" },
  { code: "cg", vi: "Congo", en: "Congo" },
  { code: "cr", vi: "Costa Rica", en: "Costa Rica" },
  { code: "hr", vi: "Croatia", en: "Croatia" },
  { code: "cu", vi: "Cuba", en: "Cuba" },
  { code: "cy", vi: "Cyprus", en: "Cyprus" },
  { code: "cz", vi: "Cộng hòa Séc", en: "Czech Republic" },
  { code: "dk", vi: "Đan Mạch", en: "Denmark" },
  { code: "dj", vi: "Djibouti", en: "Djibouti" },
  { code: "dm", vi: "Dominica", en: "Dominica" },
  { code: "do", vi: "Cộng hòa Dominica", en: "Dominican Republic" },
  { code: "ec", vi: "Ecuador", en: "Ecuador" },
  { code: "eg", vi: "Ai Cập", en: "Egypt" },
  { code: "sv", vi: "El Salvador", en: "El Salvador" },
  { code: "gq", vi: "Guinea Xích đạo", en: "Equatorial Guinea" },
  { code: "er", vi: "Eritrea", en: "Eritrea" },
  { code: "ee", vi: "Estonia", en: "Estonia" },
  { code: "sz", vi: "Eswatini", en: "Eswatini" },
  { code: "et", vi: "Ethiopia", en: "Ethiopia" },
  { code: "fj", vi: "Fiji", en: "Fiji" },
  { code: "fi", vi: "Phần Lan", en: "Finland" },
  { code: "fr", vi: "Pháp", en: "France" },
  { code: "ga", vi: "Gabon", en: "Gabon" },
  { code: "gm", vi: "Gambia", en: "Gambia" },
  { code: "ge", vi: "Georgia", en: "Georgia" },
  { code: "de", vi: "Đức", en: "Germany" },
  { code: "gh", vi: "Ghana", en: "Ghana" },
  { code: "gr", vi: "Hy Lạp", en: "Greece" },
  { code: "gd", vi: "Grenada", en: "Grenada" },
  { code: "gt", vi: "Guatemala", en: "Guatemala" },
  { code: "gn", vi: "Guinea", en: "Guinea" },
  { code: "gw", vi: "Guinea-Bissau", en: "Guinea-Bissau" },
  { code: "gy", vi: "Guyana", en: "Guyana" },
  { code: "ht", vi: "Haiti", en: "Haiti" },
  { code: "hn", vi: "Honduras", en: "Honduras" },
  { code: "hu", vi: "Hungary", en: "Hungary" },
  { code: "is", vi: "Iceland", en: "Iceland" },
  { code: "in", vi: "Ấn Độ", en: "India" },
  { code: "id", vi: "Indonesia", en: "Indonesia" },
  { code: "ir", vi: "Iran", en: "Iran" },
  { code: "iq", vi: "Iraq", en: "Iraq" },
  { code: "ie", vi: "Ireland", en: "Ireland" },
  { code: "il", vi: "Israel", en: "Israel" },
  { code: "it", vi: "Ý", en: "Italy" },
  { code: "jm", vi: "Jamaica", en: "Jamaica" },
  { code: "jp", vi: "Nhật Bản", en: "Japan" },
  { code: "jo", vi: "Jordan", en: "Jordan" },
  { code: "kz", vi: "Kazakhstan", en: "Kazakhstan" },
  { code: "ke", vi: "Kenya", en: "Kenya" },
  { code: "ki", vi: "Kiribati", en: "Kiribati" },
  { code: "kp", vi: "Triều Tiên", en: "North Korea" },
  { code: "kr", vi: "Hàn Quốc", en: "South Korea" },
  { code: "kw", vi: "Kuwait", en: "Kuwait" },
  { code: "kg", vi: "Kyrgyzstan", en: "Kyrgyzstan" },
  { code: "la", vi: "Lào", en: "Laos" },
  { code: "lv", vi: "Latvia", en: "Latvia" },
  { code: "lb", vi: "Lebanon", en: "Lebanon" },
  { code: "ls", vi: "Lesotho", en: "Lesotho" },
  { code: "lr", vi: "Liberia", en: "Liberia" },
  { code: "ly", vi: "Libya", en: "Libya" },
  { code: "li", vi: "Liechtenstein", en: "Liechtenstein" },
  { code: "lt", vi: "Lithuania", en: "Lithuania" },
  { code: "lu", vi: "Luxembourg", en: "Luxembourg" },
  { code: "mg", vi: "Madagascar", en: "Madagascar" },
  { code: "mw", vi: "Malawi", en: "Malawi" },
  { code: "my", vi: "Malaysia", en: "Malaysia" },
  { code: "mv", vi: "Maldives", en: "Maldives" },
  { code: "ml", vi: "Mali", en: "Mali" },
  { code: "mt", vi: "Malta", en: "Malta" },
  { code: "mh", vi: "Quần đảo Marshall", en: "Marshall Islands" },
  { code: "mr", vi: "Mauritania", en: "Mauritania" },
  { code: "mu", vi: "Mauritius", en: "Mauritius" },
  { code: "mx", vi: "Mexico", en: "Mexico" },
  { code: "fm", vi: "Micronesia", en: "Micronesia" },
  { code: "md", vi: "Moldova", en: "Moldova" },
  { code: "mc", vi: "Monaco", en: "Monaco" },
  { code: "mn", vi: "Mông Cổ", en: "Mongolia" },
  { code: "me", vi: "Montenegro", en: "Montenegro" },
  { code: "ma", vi: "Morocco", en: "Morocco" },
  { code: "mz", vi: "Mozambique", en: "Mozambique" },
  { code: "mm", vi: "Myanmar", en: "Myanmar" },
  { code: "na", vi: "Namibia", en: "Namibia" },
  { code: "nr", vi: "Nauru", en: "Nauru" },
  { code: "np", vi: "Nepal", en: "Nepal" },
  { code: "nl", vi: "Hà Lan", en: "Netherlands" },
  { code: "nz", vi: "New Zealand", en: "New Zealand" },
  { code: "ni", vi: "Nicaragua", en: "Nicaragua" },
  { code: "ne", vi: "Niger", en: "Niger" },
  { code: "ng", vi: "Nigeria", en: "Nigeria" },
  { code: "mk", vi: "Bắc Macedonia", en: "North Macedonia" },
  { code: "no", vi: "Na Uy", en: "Norway" },
  { code: "om", vi: "Oman", en: "Oman" },
  { code: "pk", vi: "Pakistan", en: "Pakistan" },
  { code: "pw", vi: "Palau", en: "Palau" },
  { code: "pa", vi: "Panama", en: "Panama" },
  { code: "pg", vi: "Papua New Guinea", en: "Papua New Guinea" },
  { code: "py", vi: "Paraguay", en: "Paraguay" },
  { code: "pe", vi: "Peru", en: "Peru" },
  { code: "ph", vi: "Philippines", en: "Philippines" },
  { code: "pl", vi: "Ba Lan", en: "Poland" },
  { code: "pt", vi: "Bồ Đào Nha", en: "Portugal" },
  { code: "qa", vi: "Qatar", en: "Qatar" },
  { code: "ro", vi: "Romania", en: "Romania" },
  { code: "ru", vi: "Nga", en: "Russia" },
  { code: "rw", vi: "Rwanda", en: "Rwanda" },
  { code: "kn", vi: "Saint Kitts và Nevis", en: "Saint Kitts and Nevis" },
  { code: "lc", vi: "Saint Lucia", en: "Saint Lucia" },
  { code: "vc", vi: "Saint Vincent và Grenadines", en: "Saint Vincent and the Grenadines" },
  { code: "ws", vi: "Samoa", en: "Samoa" },
  { code: "sm", vi: "San Marino", en: "San Marino" },
  { code: "st", vi: "Sao Tome và Principe", en: "Sao Tome and Principe" },
  { code: "sa", vi: "Saudi Arabia", en: "Saudi Arabia" },
  { code: "sn", vi: "Senegal", en: "Senegal" },
  { code: "rs", vi: "Serbia", en: "Serbia" },
  { code: "sc", vi: "Seychelles", en: "Seychelles" },
  { code: "sl", vi: "Sierra Leone", en: "Sierra Leone" },
  { code: "sg", vi: "Singapore", en: "Singapore" },
  { code: "sk", vi: "Slovakia", en: "Slovakia" },
  { code: "si", vi: "Slovenia", en: "Slovenia" },
  { code: "sb", vi: "Quần đảo Solomon", en: "Solomon Islands" },
  { code: "so", vi: "Somalia", en: "Somalia" },
  { code: "za", vi: "Nam Phi", en: "South Africa" },
  { code: "ss", vi: "Nam Sudan", en: "South Sudan" },
  { code: "es", vi: "Tây Ban Nha", en: "Spain" },
  { code: "lk", vi: "Sri Lanka", en: "Sri Lanka" },
  { code: "sd", vi: "Sudan", en: "Sudan" },
  { code: "sr", vi: "Suriname", en: "Suriname" },
  { code: "se", vi: "Thụy Điển", en: "Sweden" },
  { code: "ch", vi: "Thụy Sĩ", en: "Switzerland" },
  { code: "sy", vi: "Syria", en: "Syria" },
  { code: "tw", vi: "Đài Loan", en: "Taiwan" },
  { code: "tj", vi: "Tajikistan", en: "Tajikistan" },
  { code: "tz", vi: "Tanzania", en: "Tanzania" },
  { code: "th", vi: "Thái Lan", en: "Thailand" },
  { code: "tl", vi: "Timor-Leste", en: "Timor-Leste" },
  { code: "tg", vi: "Togo", en: "Togo" },
  { code: "to", vi: "Tonga", en: "Tonga" },
  { code: "tt", vi: "Trinidad và Tobago", en: "Trinidad and Tobago" },
  { code: "tn", vi: "Tunisia", en: "Tunisia" },
  { code: "tr", vi: "Thổ Nhĩ Kỳ", en: "Turkey" },
  { code: "tm", vi: "Turkmenistan", en: "Turkmenistan" },
  { code: "tv", vi: "Tuvalu", en: "Tuvalu" },
  { code: "ug", vi: "Uganda", en: "Uganda" },
  { code: "ua", vi: "Ukraine", en: "Ukraine" },
  { code: "ae", vi: "Các Tiểu vương quốc Ả Rập Thống nhất", en: "United Arab Emirates" },
  { code: "gb", vi: "Anh", en: "United Kingdom" },
  { code: "us", vi: "Mỹ", en: "United States" },
  { code: "uy", vi: "Uruguay", en: "Uruguay" },
  { code: "uz", vi: "Uzbekistan", en: "Uzbekistan" },
  { code: "vu", vi: "Vanuatu", en: "Vanuatu" },
  { code: "ve", vi: "Venezuela", en: "Venezuela" },
  { code: "ye", vi: "Yemen", en: "Yemen" },
  { code: "zm", vi: "Zambia", en: "Zambia" },
  { code: "zw", vi: "Zimbabwe", en: "Zimbabwe" }
];

export const COUNTRIES = countriesList.map(c => ({
  code: c.code.toUpperCase(),
  name: c.en
}));


export const IOC_TO_ISO2: Record<string, string> = {
  AFG: "af", ALB: "al", ALG: "dz", AND: "ad", ANG: "ao", ANT: "ag", ARG: "ar", ARM: "am", AUS: "au", AUT: "at", AZE: "az",
  BAH: "bs", BRN: "bh", BAN: "bd", BAR: "bb", BLR: "by", BEL: "be", BIZ: "bz", BEN: "bj", BHU: "bt", BOL: "bo", BIH: "ba",
  BOT: "bw", BRA: "br", BRU: "bn", BUL: "bg", BUR: "bf", BDI: "bi", CAM: "kh", CMR: "cm", CAN: "ca", CPV: "cv", CAF: "cf",
  CHA: "td", CHI: "cl", CHN: "cn", COL: "co", COM: "km", CGO: "cg", CRC: "cr", CRO: "hr", CUB: "cu", CYP: "cy", CZE: "cz",
  DEN: "dk", DJI: "dj", DMA: "dm", DOM: "do", ECU: "ec", EGY: "eg", ESA: "sv", GEQ: "gq", ERI: "er", EST: "ee", SWZ: "sz",
  ETH: "et", FIJ: "fj", FIN: "fi", FRA: "fr", GAB: "ga", GAM: "gm", GEO: "ge", GER: "de", GHA: "gh", GRE: "gr", GRN: "gd",
  GUA: "gt", GUI: "gn", GBS: "gw", GUY: "gy", HAI: "ht", HON: "hn", HUN: "hu", ISL: "is", IND: "in", INA: "id", IRI: "ir",
  IRQ: "iq", IRL: "ie", ISR: "il", ITA: "it", JAM: "jm", JPN: "jp", JOR: "jo", KAZ: "kz", KEN: "ke", KIR: "ki", PRK: "kp",
  KOR: "kr", KOW: "kw", KGZ: "kg", LAO: "la", LAT: "lv", LBN: "lb", LES: "ls", LBR: "lr", LBY: "ly", LIE: "li", LTU: "lt",
  LUX: "lu", MAD: "mg", MAW: "mw", MAS: "my", MDV: "mv", MLI: "ml", MLT: "mt", MHL: "mh", MTN: "mr", MRI: "mu", MEX: "mx",
  FSM: "fm", MDA: "md", MON: "mc", MGL: "mn", MNE: "me", MAR: "ma", MOZ: "mz", MYA: "mm", NAM: "na", NRU: "nr", NEP: "np",
  NED: "nl", NZL: "nz", NCA: "ni", NIG: "ne", NGR: "ng", MKD: "mk", NOR: "no", OMA: "om", PAK: "pk", PLW: "pw", PAN: "pa",
  PNG: "pg", PAR: "py", PER: "pe", PHI: "ph", POL: "pl", POR: "pt", QAT: "qa", ROU: "ro", RUS: "ru", RWA: "rw", SKN: "kn",
  LCA: "lc", VIN: "vc", SAM: "ws", SMR: "sm", STP: "st", KSA: "sa", SEN: "sn", SRB: "rs", SEY: "sc", SLE: "sl", SGP: "sg",
  SVK: "sk", SLO: "si", SOL: "sb", SOM: "so", RSA: "za", SSD: "ss", ESP: "es", SRI: "lk", SUD: "sd", SUR: "sr", SWE: "se",
  SUI: "ch", SYR: "sy", TPE: "tw", TJK: "tj", TAN: "tz", THA: "th", TLS: "tl", TOG: "tg", TGA: "to", TTO: "tt", TUN: "tn",
  TUR: "tr", TKM: "tm", TUV: "tv", UGA: "ug", UKR: "ua", UAE: "ae", GBR: "gb", USA: "us", URU: "uy", UZB: "uz", VAN: "vu",
  VEN: "ve", VIE: "vn", YEM: "ye", ZAM: "zm", ZIM: "zw"
};

export function convertSportCodeToIso2(sportCode: string): string {
  if (!sportCode) return "";
  const code = sportCode.toUpperCase().trim();
  return IOC_TO_ISO2[code] || code.substring(0, 2).toLowerCase();
}
